mingmingmon 1주차 과제 제출
areian13/kgu-clab-2024-2-algorithm-basic-study pull request #17
Opened 2024-10-04 14:33 UTC by mingmingmon

2024-10-05 13:10 UTC, areian13 requested changes
바꾸지 않아도 된다는 멘트가 없는 부분 모두 바꾸어 재제출해주세요 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/1. 최대공약수와 최소공배수 (16136KB, 128ms).java
> +}
뭐 손댈게 없는 완벽한 코듭니다.

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/2. 가로수(23292KB, 212ms).java
> +        }
이 문제에선 getGCD(gap[0], gap[1])을 하셔도  문제가 없습니다.
나무의 개수 n이 3개 이상이기 떄문이죠.
n = 3이라면 gap의 크기는 2가 될겁니다.
그럼 0과 1에 접근하는게 문제가 없죠.

그렇다면 만약에 크기가 0 이상인 배열의 공통 gcd를 구하라 하면 어떻게 될까요?

getGCD(x, gap[i]) = gap[i]이 되는 x를 찾아보시면 좋을 듯 합니다 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/3. 진법 변환 (14320KB, 104ms).java
> +        }
digit의 의미는 자릿수입니다.
만약 172이란 값이 들어왔을 때,
172는 3자리 숫자이고,
3번째 자릿수는 1이고,
2번째 자릿수는 7이고,
1번째 자릿수는 2이다.
이런식으로 표현합니다.

따라서 일반적으로 이 수가 몇 자리인지 표현할 땐 digit,
어떤 자릿수를 표현하고 싶을 땐 d번째 자릿수의 값은 str[d]이다.
이런 식의 변수명을 자주 씁니다.

우리가 currInt에 곱해주는 값은 b의 d제곱수입니다.
이를 표현해주는 더 적절한 표현은 power가 더 적합합니다 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/3. 진법 변환 (14320KB, 104ms).java
> +        return sum;
보통 sum이란 변수명은...
어떤 배열 안에 있는 모든 값들을 더했다.
이런 느낌이 강합니다.

우리가 위 로직을 통해 얻은 값은 단순히 숫자들을 더한 값이 아닌,
b진수 숫자를 10진수로 바꾼 것이기 때문에,
10진수를 뜻하는 decimal 혹은 dec이 더 어울립니다.

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/4. 진법 변환 2 (14448KB, 104ms).java
> +    }
직접 구현하신 부분은 칭찬할 부분이긴 하지만
알고리즘 문제를 풀다보면 reverse 함수를 호출할 일이 종종 있기도 하고,
매번 직접 구현하다보면 실수가 생길 수도 있기 때문에, 이런 부분은 라이브러리 함수를 외우는 것도 좋은 방법입니다 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/4. 진법 변환 2 (14448KB, 104ms).java
> +        }
n이 0일 경우를 고려하여 do while을 썼으면 좋겠습니다.
do while이 싫으시다면 sb가 빈 문자열일 경우에 대한 처리를 따로 해주세요.

문제에서 입력 조건으로 0이 들어오지 않을 뿐 계산기에선 너무나 당연하게 0이 입력으로 들어옵니다.
쉽게 생각하기 어려운 요소이긴 하지만 이런 것을 계속 접하다 보면 나중 가면 그것부터 찾게 됩니다 ㅎㅎ

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/5. Basically Speaking (14820KB, 128ms).java
> +}
다른 부분에서 짚었던 동일한 문제점 이외엔 훌륭합니다!
그래도 수정하시는 김에 함께 수정해주시면 좋겠네요.

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/6-1. 소수(16072KB, 120ms).java
> +        }
이 if문을 꼭 써야할까요?
다시 생각해보면 안써도 된다는 사실을 눈치챌 수 있을거예요 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/6-2 소수 (16152KB, 124ms).java
> +        isPrime[2] = true;
위와 피드백과 동일하게 2에 대해 따로 처리해주지 않아도 됩니다.

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/7-1. 소수 구하기 (20568KB, 452ms).java
> +}
위와 동일한 문제점 외엔 훌륭히 해결하셨습니다.

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/7-2. 소수 구하기 (24436KB, 316ms).java
> +    public static final int SIZE = 1000000;
흠 C++은 리터럴 숫자를 표현할 때 1'000'000'000처럼 따옴표로 숫자를 작성할 수 있습니다.
그래서 자바도 있나 찾아봤는데 자바는 _ 이 언더바로 할 수 있다네요...
1_000_000_000 흠... 좀 못생기긴 했는데 그래도 알아놓고 나중에 긴 숫자 쓸 때 좋을 것 같아서 알려드립니다.
얜 굳이 바꿀 필요 없어보입니다 :)

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/7-2. 소수 구하기 (24436KB, 316ms).java
> +        }
어... 우리가 최적화를 위해 노오오력했던 것 중 하나가 빠진 것 같아요!

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/7-2. 소수 구하기 (24436KB, 316ms).java
> +
오잉 여긴 2에 대해 처리를 안해주셨구만유
안 쓰는게 정배이니 안바꾸는게 맞습니다 ^^

2024-10-05 13:10 UTC, areian13 commented on 1주차/과제/mingmingmon/8. 내부 라이브러리 조사.txt
> +System.out.println(num);
자세히 찾아보셨네요!
제가 위에서 말씀드렸던 reverse에 대해서도 찾아보시면 좋을 것 같아요!
이 부분은 재제출하실 필요는 없습니다.

2024-10-07 04:03 UTC, areian13 requested changes
1번 과제에 수정사항 하나 더 있습니다.

2024-10-07 04:03 UTC, areian13 commented on 1주차/과제/mingmingmon/2. 가로수(23292KB, 212ms).java
> +        }
배열의 크기가 0이면 gap[0]을 할 수 없습니다.

2024-10-07 04:05 UTC, areian13 requested changes

2024-10-07 04:05 UTC, areian13 commented on 1주차/과제/mingmingmon/2. 가로수(23292KB, 212ms).java
> +        int resultGap = gap[0];
배열의 크기가 0일 땐 gap[0]을 할 수 없습니다.

2024-10-07 04:07 UTC, mingmingmon commented on 1주차/과제/mingmingmon/2. 가로수(23292KB, 212ms).java
> +        int resultGap = gap[0];
getGCD(x, gap[i]) = gap[i] 가 되는 x를 찾아내는 것까지 해결했습니다!
다만 코멘트내용에 따라서 크기가 0인 경우에는 int[] gap이 선언될 수 없는 상황일 것 같아요. 이 경우에 대해서도 일반화된 코드를 짤 수 있다는 말씀이실까요??

2024-10-07 04:09 UTC, areian13 commented on 1주차/과제/mingmingmon/2. 가로수(23292KB, 212ms).java
> +        int resultGap = gap[0];
x가 gap[i]인 것이라 생각하신 것 같고, 틀린 말은 아니지만 제가 의도했던건 0이었습니다.
GCD(0, n) = n이 나오니까요.
문제의 조건에선 나올 수 없는 환경이라도 충분히 다른 문제에서 등장 가능한 조건에 한해서는 웬만하면 모두 사용 가능하도록 일반화 하는 것이 좋습니다.
(가끔 특별한 입력 조건에 의한 풀이를 의도한 문제가 있긴 합니다.)

2024-10-07 04:17 UTC, areian13 approved these changes
수고하셨습니다!

2024-10-07 04:18 UTC, merged